--- 
before_script: 
  - "psql -c 'create database {{.opts.App.Name.File}}_test;' -U postgres"
  - "mkdir -p $TRAVIS_BUILD_DIR/public/assets"
env: 
  - GO_ENV=test
  - GO111MODULE=on
go: 
  - 1.12.x
go_import_path: 
  ? 
    .opts.App.PackagePkg: ~
  : ~
install: 
  - "go get github.com/gobuffalo/buffalo/buffalo"
language: go
script: "buffalo test"
services: 
  - postgresql